CLASS MANAGER/Controllers/StudentMaintainerController.cs
using Microsoft.AspNetCore.Mvc;
using CLASS_MANAGER.Data;
using CLASS_MANAGER.Models;
using Microsoft.AspNetCore.Authorization;

namespace CLASS_MANAGER.Controllers {

    
    public class StudentMaintainerController : Controller
    {
        StudentsData _studentsData = new StudentsData();

        [Authorize(Roles ="Teacher,Coordinator,Supervisor")]
        public IActionResult ListStu()
        {
            var oListStu = _studentsData.StuList();
            return View(oListStu);
        }

        //-----------------------Only returns view------------>

        [Authorize(Roles = "Coordinator,Supervisor")]
        public IActionResult SaveStu()
        {
            return View();
        }

        //----------------------Saves Students---------------->
        [HttpPost]
        public IActionResult SaveStu(StudentsModel Stu)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            var ans = _studentsData.SaveStu(Stu);

            if (ans)
            {
                return RedirectToAction("ListStu");
            }
            else
            {
                return View();

            }
         }

        [Authorize(Roles = "Coordinator,Supervisor")]
        public IActionResult EditStu(int studentID)
        {
            var student = _studentsData.GetStu(studentID);
            return View(student);
        }

        [HttpPost]
        public IActionResult EditStu(StudentsModel oStu)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var ans = _studentsData.EditStu(oStu);

            if (ans)
            {
                return RedirectToAction("ListStu");
            }
            else
            {
                return View();

            }
        }

        [Authorize(Roles = "Coordinator,Supervisor")]
        public IActionResult DelStu(int studentID)
        {
            var oStu = _studentsData.GetStu(studentID);
            return View(oStu);
        }
        
        [HttpPost]
        public IActionResult DelStu(StudentsModel oStu)
        {
            var ans = _studentsData.StuDel(oStu.StudentID);

            if (ans)
            {
                return RedirectToAction("ListStu");
            }
            else
            {
                return View();
            }

            
        }

    }
}

CLASS MANAGER/Views/StudentMaintainer/DelStu.cshtml
@model StudentsModel;
@{
    ViewData["Title"] = "DelStu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card w-75">
    <div class="card-body">
        <h5 class="card-title">DELETE STUDENT</h5>
        <hr />
        <form method="post" asp-action="DelStu" asp-controller="StudentMaintainer">
            <input type="hidden" class="form-control" id="exampleInputEmail1" asp-for="StudentID">
            <div class="alert alert-danger" role="alert">
                Are you sure you want to delete @Html.DisplayTextFor(m=>m.StuName) from roster?
            </div>

            <button type="submit" class="btn btn-primary">Delete</button>
            <a asp-action="ListStu" asp-controller="StudentMaintainer" class="btn btn-warning">Cancel</a>
        </form>


    </div>
</div>

CLASS MANAGER/Views/StudentMaintainer/EditStu.cshtml
@model StudentsModel;
@{
    ViewData["Title"] = "EditStu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card w-75">
    <div class="card-body">
        <h5 class="card-title">EDIT STUDENT</h5>
        <hr />
        <form method="post" asp-action="EditStu" asp-controller="StudentMaintainer">
            <input type="hidden" class="form-control" id="exampleInputEmail1" asp-for="StudentID">
            <div class="mb-3">
                <label class="form-label">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" asp-for="StuName">
                <div id="emailHelp" class="form-text">Make sure to type student's name as it appears on their ID</div>
                <span asp-validation-for="StuName" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Lastname</label>
                <input type="text" class="form-control" id="exampleInputPassword1" asp-for="StuLast">
                <span asp-validation-for="StuLast" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputPassword1" asp-for="StuMail">
                <span asp-validation-for="StuMail" class="text-danger"></span>
            </div>
            <div class="mb-3">
                <label class="form-label">Cedula/ID</label>
                <input type="text" class="form-control" placeholder="Example: 402-1234566-7" id="exampleInputPassword1"
                       asp-for="StuCed">
                <span asp-validation-for="StuCed" class="text-danger"></span>
            </div>


            <button type="submit" class="btn btn-primary">Confirm edit</button>
            <a asp-action="ListStu" asp-controller="StudentMaintainer" class="btn btn-warning">Go back to roster</a>
        </form>


    </div>
</div>

CLASS MANAGER/Views/StudentMaintainer/ListStu.cshtml
@model List<StudentsModel>
@{
    ViewData["Title"] = "ListStu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="card bg-dark text-white">
    <img src="~/images/pexels-buro-millennial-1438072.jpg" class="card-img" alt="...">
    <div class="card-img-overlay">
        <h5 class="card-title">STUDENT ROSTER</h5>
        <hr />
        <a asp-action="SaveStu" asp-controller="StudentMaintainer" class="btn btn-success">Add a new student</a>
        <hr />
        <div class="card">
            <div class="card-header">             
            </div>
            <div class="card-body">
                <table class="table table-bordered ">


                    <thead class="table-dark">
                        <tr>
                            <th>Name</th>
                            <th>Lastname</th>
                            <th>Email</th>
                            <th>Cedula/ID</th>
                            <th>

                            </th>
                        </tr>
                    </thead>

                    @foreach (var i in Model)
                    {

                        <tr>
                            <td>@i.StuName</td>
                            <td>@i.StuLast</td>
                            <td>@i.StuMail</td>
                            <td>@i.StuCed</td>
                            <td>
                                <a asp-action="EditStu" asp-controller="StudentMaintainer" class="btn btn-primary btn-sm" asp-route-studentID="@i.StudentID">Edit</a>
                                <a asp-action="DelStu" asp-controller="StudentMaintainer" class="btn btn-danger btn-sm" asp-route-studentID="@i.StudentID">Delete</a>
                            </td>
                        </tr>
                    }
                </table>
            </div>
        </div>
        

    </div>
</div>

CLASS MANAGER/Views/StudentMaintainer/SaveStu.cshtml
@model StudentsModel;
@{
    ViewData["Title"] = "SaveStu";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card w-75">
    <div class="card-body">
        <h5 class="card-title">REGISTER NEW STUDENT</h5>
        <hr/>
        <form method="post" asp-action="SaveStu" asp-controller="StudentMaintainer"> 
                    <div class="mb-3">
                        <label  class="form-label">Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" asp-for="StuName">
                        <div id="emailHelp" class="form-text">Make sure to type student's name as it appears on their ID</div>
                        <span asp-validation-for="StuName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label  class="form-label">Lastname</label>
                <input type="text" class="form-control" id="exampleInputPassword1" asp-for="StuLast">
                <span asp-validation-for="StuLast" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Email</label>
                <input type="email" class="form-control" id="exampleInputPassword1" asp-for="StuMail">
                <span asp-validation-for="StuMail" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Cedula/ID</label>
                        <input type="text" class="form-control" placeholder="Example: 402-1234566-7" id="exampleInputPassword1"
                        asp-for="StuCed">
                <span asp-validation-for="StuCed" class="text-danger"></span>
                    </div>

                    
                    <button type="submit" class="btn btn-primary">Add to roster</button>
                    <a asp-action="ListStu" asp-controller="StudentMaintainer" class="btn btn-warning">Go back to roster</a>
                </form>

        
    </div>
</div>